spring:
  jpa:
    properties:
        format_sql: 'TRUE'
    hibernate:
      ddl-auto: update
    open-in-view: 'false'

  sql:
    init:
      mode: never

  mvc:
    hiddenmethod:
      filter:
        enabled: 'true'
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    password: ${db_password}
    username: ${db_username}
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/aloevibe?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC
logging:
  level:
    org:
      hibernate:
        type:
          descriptor: TRACE
        SQL: DEBUG
      nodeValue: WARN
    blog: WARN

security:
  remembered:
    key: ${remember_me_key}

admin:
  password: ${admin_password}
  email: ${admin_email}

recaptcha:
  siteKey: ${recaptcha_siteKey}
  secretKey: ${recaptcha_secretKey}

server:
  port: ${server_port}
